// Otros tipos.
global using Http.ResponsesList;
global using LIN.Communication.Memory;
global using LIN.Communication.Services;
global using LIN.Types.Cloud.Identity.Abstracts;
global using LIN.Types.Communication.Enumerations;
// Tipos locales.
global using LIN.Types.Communication.Models;
global using LIN.Types.Cloud.OpenAssistant.Api;
global using LIN.Types.Enumerations;
global using LIN.Types.Responses;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.EntityFrameworkCore;